server:
  port: 8000
spring:
  profiles: dev
  application:
    name: springboot-mybatis
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-mybatis?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml #mybatis基础配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml #mybatis实体类映射文件

logging:
  level:
      com:
        yipinketang:
          app:
            mapper: debug #打印sql日志
